import type { Metadata } from "next";
import { IBMPlexMono, Inter, JetbrainsMono } from "@/styles/fonts";
import "@/styles/globals.css";
import { Providers } from "./providers";

export const metadata: Metadata = { title: "Create Next App", description: "Generated by create next app" };

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en" className={`${IBMPlexMono.variable} ${Inter.variable} ${JetbrainsMono.variable}`}>
			<body>
				<Providers>{children}</Providers>
			</body>
		</html>
	);
}
