services:

  postgres:
    image: postgres:latest
    container_name: "echo_postgres"
    restart: no # for development, no need to auto restart
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data

  redis:
    image: "redis/redis-stack:latest"
    container_name: "echo_redis"
    restart: no # for development, no need to auto restart
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - ./redis_data:/data